### ISSUE TITLE
Running Synplex w/ Default Parameters

### ISSUE THREAD

**Issue by simonwarchol** [djimenezsanchez/Synplex#1]
Hi There,
I'm a graduate student at the Harvard University School Of Engineering And Applied Sciences. I'm currently looking into ways of generating synthetic multiplexed imaging data, ideally at a sub-cellular resolution. 
I'm trying to run Synplex out of the box without changing anything and am encountering some issues:
I've had to comment out many of the visualization components because of out-of-index errors
e.g. 
```Index exceeds the number of array elements. Index must not exceed 5.

Error in Parameters_Visualization_Phenotypes (line 6)
    h = heatmap(CellPhenotypeNames([4,6,7]),CellPhenotypeNames([4,6,7]),CellPhenotypeInteraction([4,6,7],[4,6,7],2),'Colormap',jet,'ColorLimits',[0 1]);
```

once I do this, I'm able to train the model, but am now getting the following error, which seems to think there are more than 3 rows in the `Phenotype_Abundance` matrix
```
Index in position 1 exceeds array bounds. Index must not exceed 3.

Error in Modeling_phenotypes (line 88)
        CellCellInter(:,:,iNb) = CellPhenotypeInteraction(:,:,iNb).*(((Phenotype_Abundance(iNb,:)*100)./Perc_Nb_Pheno(iNb,2:end)).^3);

Error in main (line 30)
    last_step_phenotypes = Modeling_phenotypes(BasefolderName,LoadfolderName,...
```

Do you have any guidance to get this working? Happy to provide more information if necessary.
-Simon

**Comment by djimenezsanchez** [comment]
Dear Simon, 

thanks for reaching out. I believe that Synplex could be useful for your case, simulating multiplexed imaging data at sub-cellular resolution. To this end, you can tune cell size, nucleus to cell ratio, and nucleus/cytoplasm marker localization.

With regards to the issues you are encountering, I´ve downloaded and executed the code out-of-the-box as you did. Unfortunately, there was some legacy code that did not work with the default parameters. I´ve fixed that, you can download the new version. 

I´ve run it without any issues. Using the default parameters you should get an image like this: 
![image](https://user-images.githubusercontent.com/43730952/183054461-4ecba7a5-dc31-4206-bdd0-f173bd1b8a3d.png)

where blue is DAPI (staining nuclear DNA), red is cytokeratin (staining tumor cells), and green is CD8 (staining T cells).

Hope this helps!

Please do not hesitate to contact me in case you need help tuning the parameters of the simulator. 

Best,
Daniel.

**Comment by simonwarchol** [comment]
Hey Daniel,
Wow! thank you SO much for the swift response. Trying the new version right now, will let you know if I have any other questions.
Best,
Simon
